tests:
	lein test homework.binarysearch-test \
	 homework.cakecutting-test \
	 homework.calculus-test \
	 homework.determinant-test \
	 homework.factors-test \
	 homework.frenchnames-test \
	 homework.hello-test \
	 homework.polynomial-test \
	 homework.recursion-test \
	 homework.reduce-test \
	 homework.runaverage-test \
	 homework.theg-test \
	 homework.trig-test \
	 homework.triptych-test
