test:
	lein test homework.binarysearch-test
	lein test homework.cakecutting-test
	lein test homework.determinant-test
	lein test homework.factors-test
	lein test homework.frenchnames-test
	lein test homework.hello-test
	lein test homework.polynomial-test
	lein test homework.recursion-test
	lein test homework.reduce-test
	lein test homework.runaverage-test
	lein test homework.theg-test
	lein test homework.trig-test
	lein test homework.triptych-test
